### PR TITLE
fix(@clayui/date-picker): When selecting a date using space key, removes properly the `:active` state of the element

### LINKED ISSUE #3374: When navigating on DatePicker via TABS and selecting dates with SPACE, we can multi select days
-   [✅ ] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

Just use the master's storybook: https://storybook-clayui.netlify.app/?path=/story/components-claydatepicker--default

## What are the steps to reproduce?

Open ClayDatePicker using space, then navigate thru dates using TABS and select using SPACE.

You'll notice is possible select multiple dates(at least the UI tells it 😂 )

Screen Shot 2020-06-29 at 14 58 45

## What is the expected result?

Since We don't have a design specification for multi select dates, don't let user select multiple dates

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.4.0  |
| React | `undefined` |

### PR DESCRIPTION
**Pull request by diegonvs**
## Test Case

1. Open our Date Picker component on storybook: https://storybook.clayui.com/?path=/story/components-claydatepicker--default
2. Navigate thru days using tabs and select a day using SPACE key
3. Navigate faster thru days and try to select multiple days using SPACE key
4. You will able to select multiple days when using SPACE key

----

For solving this problem, the keyDown event when the space key is pressed was prevented and when keyUp, the click callback was called.

## Commits

- chore(@clayui/date-picker): Prefer destructuring
- fix(@clayui/date-picker): When selecting a date using space key, removes properly the `:active` state of the element. This issue can't be reproduced on IE/FF but it can be reproduced on Chrome/Safari. Apparently this is a WebKit issue

Closes #3374

### CODE REVIEW

File: packages/clay-date-picker/src/DayNumber.tsx [hunk 1]
```diff
@@ -41,11 +51,28 @@ const ClayDatePickerDayNumber: React.FunctionComponent<IProps> = ({
...
 			className={classNames}
-			disabled={day.outside}
-			onClick={() => onClick(day.date)}
+			disabled={outside}
+			onClick={() => onClick(date)}
+			onKeyDown={(event) => {
+				// When tabbing and selecting a DayNumber using
+				// SPACE key the active state it's not being removed.
+				// See https://github.com/liferay/clay/issues/3374 for more details.
+				if (event.keyCode === KEY_CODE_SPACE) {
```
Comment (pat270) [inline packages/clay-date-picker/src/DayNumber.tsx:60]: When I was looking up the keycode stuff, I saw a big red alert on MDN I didn't pay attention to. It looks like `event.keyCode` is gone. They recommend using `event.code` (not supported in IE) and `event.key`. I think the right way going forward is:
```
if (event.key === ' ' || event.key === 'Spacebar') {}
```

**Comment by kresimir-coko** [comment]
Hey @diegonvs I've fired up the storybook with your changes and they do have the desired effect, I couldn't select 2 dates at the same time when going fast. LGTM

File: packages/clay-date-picker/src/DayNumber.tsx (hunk 1 above)
Comment (matuzalemsteles) [reply packages/clay-date-picker/src/DayNumber.tsx:60]: 😱 my +1 for that

File: packages/clay-date-picker/src/DayNumber.tsx [hunk 2]
```diff
@@ -13,26 +13,36 @@ interface IProps {
...
+const KEY_CODE_SPACE = 32;
+
 const ClayDatePickerDayNumber: React.FunctionComponent<IProps> = ({
 	day,
 	daySelected,
 	disabled,
-	onClick,
+	onClick = noop,
+	onKeyDown = noop,
+	onKeyUp = noop,
```
Comment (matuzalemsteles) [inline packages/clay-date-picker/src/DayNumber.tsx:30]: I think we don't need to keep adding `noop` ​​all the time here, I would avoid that. Since this is a component that is only used in the DatePicker, we don't need noop. We may not even need `onKeyDown` and `onKeyUp` for this case since we are not using it. If this were a public component it would make more sense.

File: packages/clay-date-picker/src/DayNumber.tsx [hunk 3]
```diff
@@ -41,11 +51,28 @@ const ClayDatePickerDayNumber: React.FunctionComponent<IProps> = ({
...
+
+				onKeyDown(event);
+			}}
+			onKeyUp={(event) => {
+				if (event.keyCode === KEY_CODE_SPACE) {
+					onClick(date);
+				}
+
+				onKeyUp(event);
+			}}
```
Comment (matuzalemsteles) [inline packages/clay-date-picker/src/DayNumber.tsx:72]: One question: this just to retrieve the `space` event that we gave `preventDefault` before?

File: packages/clay-date-picker/src/DayNumber.tsx (hunk 1 above)
Comment (diegonvs) [reply packages/clay-date-picker/src/DayNumber.tsx:60]: Thanks for pointing up this Pat. I didn't noticed keyCode isn't recommended more. 

Apparently We're using on Clay in these files:

https://gist.github.com/diegonvs/89654431236967272f4ff3bfc43b8311

Ignoring clay-css/jquery related usages, We're using on the Modal, MultiSelect and on our FocusScope component.

I consider replacing this usages with `.key` the best option but I think We must pay attention in 

> `Has non-standard key identifiers and incorrect behaviour with AltGraph.`

from: https://caniuse.com/#feat=keyboardevent-key

I'll fill an issue for replacing this usages and I'll use `.key` on this PR

Comment (matuzalemsteles) [reply packages/clay-date-picker/src/DayNumber.tsx:60]: Yeah, I didn't know that either. This is also used a lot on the Portal. cc @wincent maybe we should create a recommendation in the guidelines to use `key` and `code` instead of `keyCode`?

Comment (diegonvs) [reply packages/clay-date-picker/src/DayNumber.tsx:60]: Bringing eslint-unicorn-plugin cool insights, https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-event-key.md. Can we enforce this on our eslint config?

Comment (jbalsas) [reply packages/clay-date-picker/src/DayNumber.tsx:60]: > Bringing eslint-unicorn-plugin ™️ cool insights, https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-event-key.md.

nogodno

> Can we enforce this on our eslint config?

Probably yes 😉

Comment (diegonvs) [reply packages/clay-date-picker/src/DayNumber.tsx:60]: https://github.com/liferay/clay/issues/3430

File: packages/clay-date-picker/src/DayNumber.tsx (hunk 2 above)
Comment (diegonvs) [reply packages/clay-date-picker/src/DayNumber.tsx:32]: Yes, makes sense Matu. Since We're not exposing directly this component, I'll remove these noops. :)

File: packages/clay-date-picker/src/DayNumber.tsx (hunk 3 above)
Comment (diegonvs) [reply packages/clay-date-picker/src/DayNumber.tsx]: Yes, when keyDown, We're preventing and when SPACE key is released, onClick cb will be called.

File: packages/clay-date-picker/src/DayNumber.tsx (hunk 2 above)
Comment (diegonvs) [reply packages/clay-date-picker/src/DayNumber.tsx:32]: > We may not even need onKeyDown and onKeyUp for this case since we are not using it. If this were a public component it would make more sense.

So, Should I remove from props interface?

Comment (diegonvs) [reply packages/clay-date-picker/src/DayNumber.tsx]: Removed after some internal conversations

File: packages/clay-date-picker/src/DayNumber.tsx [hunk 4]
```diff
@@ -41,11 +47,24 @@ const ClayDatePickerDayNumber: React.FunctionComponent<IProps> = ({
...
 			className={classNames}
-			disabled={day.outside}
-			onClick={() => onClick(day.date)}
+			disabled={outside}
+			onClick={() => onClick(date)}
+			onKeyDown={(event) => {
+				// When tabbing and selecting a DayNumber using
+				// SPACE key the active state it's not being removed.
+				// See https://github.com/liferay/clay/issues/3374 for more details.
+				if (event.key === KEYS.SPACE) {
```
Comment (matuzalemsteles) [inline packages/clay-date-picker/src/DayNumber.tsx:56]: @diegonvs we should probably also check out "Spacebar" here.

> [1] Older browsers may return "Spacebar" instead of " " for the Space Bar key. Firefox did so until version 37, as did Internet Explorer 9, 10, and 11.
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

Comment (jbalsas) [reply packages/clay-date-picker/src/DayNumber.tsx:56]: spacebar

https://www.threadless.com/product/2574/spacebar

File: packages/clay-date-picker/src/DayNumber.tsx (hunk 1 above)
Comment (wincent) [reply packages/clay-date-picker/src/DayNumber.tsx]: > Yeah, I didn't know that either. This is also used a lot on the Portal. cc @wincent maybe we should create a recommendation in the guidelines to use `key` and `code` instead of `keyCode`?

Guidelines are cool and all, but I'd much rather have a code abstraction that guides people to use "the right tool". Lint enforcing the use of the tool is a bonus that may be necessary if discoverability of the abstraction isn't good enough. Guidelines are useful support, but let's not kid ourselves that a document in a GitHub repo will stop "Random Product Team X" from shipping something we don't want into "Secret DXP Directory Z".

About the eslint-plugin-unicorn rule, I would steer clear of it. Apart from the undesirability of [the dependency footprint](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/6c02ce4e32c84702bcd06e90aa91696366036294/package.json#L35-L49), I don't think it's going to help us avoid the issues with IE compat noted on #3430 (see [the implementation](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/6c02ce4e32c84702bcd06e90aa91696366036294/rules/prefer-event-key.js#L13-L60), which assumes non-IE browser).

So I'd provisionally say:

scooby-no

And suggest that if we care about linting, we might even want to make our own.

File: packages/clay-date-picker/src/DayNumber.tsx (hunk 4 above)
Comment (diegonvs) [reply packages/clay-date-picker/src/DayNumber.tsx:56]: See 64af3da

File: packages/clay-date-picker/src/DayNumber.tsx [hunk 5]
```diff
@@ -15,24 +15,30 @@ interface IProps {
 	onClick: (date: Date) => void;
 }
 
+const KEYS = {
+	SPACE: ('Spacebar' || ' '),
```
Comment (matuzalemsteles) [inline packages/clay-date-picker/src/DayNumber.tsx:19]: @diegonvs I think that this will not work to check both, we have to make explicit in the `if` conditional below. What we are doing here is conditional if `Spacebar` does not exist which will never be true.

Comment (wincent) [reply packages/clay-date-picker/src/DayNumber.tsx:19]: TS39 proposal: New binary operator, `││` (2 x Unicode U+2502, "Box Drawings Light Vertical"), which represents the quantum superposition of the left and right side operands.

Comment (matuzalemsteles) [reply packages/clay-date-picker/src/DayNumber.tsx:19]: 🤔 Hmm

Comment (diegonvs) [reply packages/clay-date-picker/src/DayNumber.tsx:19]: I was minding https://en.wikipedia.org/wiki/Distributive_property 🤔
