### PR TITLE
fix(@clayui/icon): forces React not to reuse node when symbol changes

### LINKED ISSUE #2642: Changing ClayIcon Symbol Inside Portal Causes Problems
DXP uses `svg4everybody` to avoid **cors** issues with external links, it makes an Ajax request and replaces `svg:use`.

Since we have ClayIcon in React, changing the `symbol` inside DXP causes it not to be changed because React reuses node to make changes. This only works the first time.

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes #2642

As suggested by @jbalsas, it was the same solution in Metal. Forces to change the `key` of the element so that React does not reuse the node, so `svg4everybody` will re-capture the node to make its changes.

I am adding this straight to `ClayIcon` because it is common for someone to do this and so we can support it directly, I don't see a real problem with that so please let me know if you see anything.

Once we get on with this, we will need to release some fix patches for the components that use the ClayIcon. I'm eyeing ColorPicker that symbol change...

### CODE REVIEW

File: packages/clay-icon/src/index.tsx [hunk 1]
```diff
@@ -43,6 +43,7 @@ const ClayIcon = React.forwardRef<SVGSVGElement, IProps>(
 					`lexicon-icon lexicon-icon-${symbol}`,
 					className
 				)}
+				key={symbol}
```
Comment (bryceosterhaus) [inline packages/clay-icon/src/index.tsx]: Should we also add a useEffect so that the component doesnt re-render unless symbol or one of the other props changes?

Comment (wincent) [reply packages/clay-icon/src/index.tsx]: I don't think `useEffect` is really needed or desirable here.

Comment (matuzalemsteles) [reply packages/clay-icon/src/index.tsx]: Hmm, not sure about `useEffect`... why would we use it?

Comment (bryceosterhaus) [reply packages/clay-icon/src/index.tsx]: oh i mis-read your original post. I thought you were adding this to avoid re-renders, but i see now that its for not re-using the node.
