### PR TITLE
fix(@clayui/drop-down): add `alignmentPosition` support in DropDownWithItems

### LINKED ISSUE #2647: `DropDownWithItems` does not support the `alignmentPosition` attribute
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
Create a `DropDownWithItems` and give it the attribute `alignmentPosition={Align.BottomRight}`.

## What is the expected result?
The resulting dropdown will be aligned according to the attribute value.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0.0  |
| React | v16.9.0 |

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes #2647

### CODE REVIEW

File: packages/clay-drop-down/src/DropDownWithItems.tsx [hunk 1]
```diff
@@ -246,6 +251,7 @@ const DropDownContent: React.FunctionComponent<IDropDownContentProps> = ({
 );
 
 export const ClayDropDownWithItems: React.FunctionComponent<IProps> = ({
+	alignmentPosition,
```
Comment (bryceosterhaus) [inline packages/clay-drop-down/src/DropDownWithItems.tsx]: we might just want to add `dropDownProps` since we also might want to give the option for "autoBestAlign" and any others that come up. wdyt?

Comment (matuzalemsteles) [reply packages/clay-drop-down/src/DropDownWithItems.tsx]: Hmm, if we do that we will have to make changes to much of the current `DropDownWithItems` API, for example we have `containerElement`, `trigger` and `className`, the other APIs we are covering with internal implementations (`hasLeftSymbols`,` hasRightSymbols`, `onActiveChange`, `active`). So it can be a little misleading to have a `dropDownProps` and we will need to move all the APIs there.

Comment (bryceosterhaus) [reply packages/clay-drop-down/src/DropDownWithItems.tsx]: We could  omit any internal props we use from that interface. This would help give a straight forwardness to what props people can actually use and then make sure `dropDownProps` is the first item spread into its props, so that our internal uses are covered.

Comment (matuzalemsteles) [reply packages/clay-drop-down/src/DropDownWithItems.tsx]: Yeah I have no problem omitting it just a bit weird having a `dropDownProps` prop that refers to DropDown props on a component that is high-level DropDown, it seems simpler to see APIs like this as a component host without having to be passed to a specific prop...

Maybe we can extend from `ClayDropDown` and use `otherProps` to switch to `ClayDropDown` since it is the main component of `ClayDropDownWithItems`. And we can omit the internal uses of `ClayDropDown`.

Comment (bryceosterhaus) [reply packages/clay-drop-down/src/DropDownWithItems.tsx]: oh thats a good point, I didnt think of it that way. So actually, in that case I think I am fine with the implementation as is. If we find ourselves needing additional props in the future we can extend from dropdown and spread otherProps, this would keep the same compatibility as well.

So overall, this PR looks good to me.

Comment (matuzalemsteles) [reply packages/clay-drop-down/src/DropDownWithItems.tsx]: Yeah, sounds good. I will go ahead with this PR.
