### PR TITLE
fix(@clayui/date-picker): adds the API to disable date picker features

### LINKED ISSUE #3045: DatePicker: Make it possible to disable the DatePicker and listen to onFocus and onBlur events
I'm migrating from DDM to use the new DatePicker in Clay's React, but we need some features like disabling DatePicker and listening for input events.

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes #3045

### CODE REVIEW

File: packages/clay-date-picker/src/InputDate.tsx [hunk 1]
```diff
@@ -55,7 +58,9 @@ const ClayDatePickerInputDate: React.FunctionComponent<IProps> = ({
 		<>
 			<input name={inputName} type="hidden" value={memoizedValue} />
 			<ClayInput
+				{...otherProps}
 				aria-label={ariaLabel}
+				disabled={disabled}
```
Comment (bryceosterhaus) [inline packages/clay-date-picker/src/InputDate.tsx]: Since we are already using `{...otherProps}`, we don't need to explicitly set `disabled` or use it off of the props anymore

Comment (bryceosterhaus) [reply packages/clay-date-picker/src/InputDate.tsx]: We can also probably remove other explicit props like `placeholder` and `onChange`. Unless they are used elsewhere.

Comment (matuzalemsteles) [reply packages/clay-date-picker/src/InputDate.tsx]: Oh yeah, I'll clean it up.

**Comment by matuzalemsteles** [comment]
@bryceosterhaus updated.
