### PR TITLE
fix(@clayui/card): When pressing `enter` or `space`, triggers a click event on CardWithNavigation

### LINKED ISSUE #3365: @clayui/card is not clickable with keyboard
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

[This example](https://codesandbox.io/s/interesting-driscoll-g66ot) uses `ClayCardWithNavigation` with an onClick handler.

I've seen that ClayCard uses a `div` with `role=button` internally when the card should be interactive, and using this markup instead of a regular `button` tag doesn't have the same browser behavior.

## What are the steps to reproduce?

1. Use `ClayCardWithNavigation` with an `onClick` prop.
2. Navigate to the component using keyboard `tabbing`
3. Press `enter`/`space` key

## What is the expected result?

onClick handler is executed.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay Card  | v3.2.1  |
| React | 16.10.2 |

### PR DESCRIPTION
**Pull request by diegonvs**
## Test Case

> Open Storybook on CardWithNavigation story: https://storybook.clayui.com/?path=/story/components-claycard--cardwithnavigation, try to focus the onClick card and then press SPACE or ENTER key.

The original behaviour is when a button is focused, this element be triggered by SPACE or a ENTER key but when using a div with a role="button" this isn't possible.

## Description

I needed to hack the onKeyDown event for detecting a SPACE or ENTER keydown event passing the event of keydown for these keys to onClick callback.

## Questions/Issues:

Is there a way for avoiding using a div with a role="button" attribute? /cc @pat270

See https://twitter.com/scottohara/status/1183020913509502978

Closes #3365

### CODE REVIEW

File: packages/clay-card/src/CardWithNavigation.tsx [hunk 1]
```diff
@@ -64,7 +74,19 @@ export const ClayCardWithNavigation: React.FunctionComponent<IProps> = ({
...
+					(event && event.keyCode === KEYCODES.ENTER) ||
+					(event && event.keyCode === KEYCODES.SPACE)
+				) {
+					event.preventDefault();
+
+					if (onClickCallback) {
+						onClickCallback(event);
+					}
+				}
+			}}
```
Comment (matuzalemsteles) [inline packages/clay-card/src/CardWithNavigation.tsx:89]: I think we should always call `onKeyDown` callback here.

File: packages/clay-card/src/CardWithNavigation.tsx [hunk 2]
```diff
@@ -49,13 +54,18 @@ interface IProps {
...
+};
+
 export const ClayCardWithNavigation: React.FunctionComponent<IProps> = ({
 	children,
 	description,
 	horizontal = false,
 	horizontalSymbol = '',
 	href,
-	onClick,
+	onClick: onClickCallback,
```
Comment (matuzalemsteles) [inline packages/clay-card/src/CardWithNavigation.tsx:68]: Why not just keep `onClick`?

Comment (diegonvs) [reply packages/clay-card/src/CardWithNavigation.tsx:68]: I forgot to remove this alias, I was using in a older implementation 😅

File: packages/clay-card/src/CardWithNavigation.tsx (hunk 1 above)
Comment (diegonvs) [reply packages/clay-card/src/CardWithNavigation.tsx:89]: If We change the element to a button, yes.

> The original behaviour is when a button is focused, this element be triggered by SPACE or a ENTER key but when using a div with a role="button" this isn't possible.

Comment (matuzalemsteles) [reply packages/clay-card/src/CardWithNavigation.tsx:89]: What I'm saying is, regardless of not going to `button`, we should allow people to add `onKeyDown` listeners here.

File: packages/clay-card/src/CardWithNavigation.tsx (hunk 2 above)
Comment (matuzalemsteles) [reply packages/clay-card/src/CardWithNavigation.tsx:68]: haha np

File: packages/clay-card/src/CardWithNavigation.tsx (hunk 1 above)
Comment (diegonvs) [reply packages/clay-card/src/CardWithNavigation.tsx:89]: Oh, gotcha.

**Comment by pat270** [comment]
@diegonvs @matuzalemsteles sorry I missed this. The problem of wrapping the card in `button` or `a` is that form elements, buttons, or other links aren't valid inside those tags. We should use `div` because we stuff so much in our cards.

The way I think it should work is `<div tabindex="0" role="button">` should dispatch a click event when keydown is enter.

**Comment by matuzalemsteles** [comment]
Thanks @pat270, for the info.

File: packages/clay-card/package.json [hunk 3]
```diff
@@ -32,6 +32,7 @@
 		"@clayui/label": "^3.3.1",
 		"@clayui/layout": "^3.1.0",
 		"@clayui/link": "^3.2.0",
+		"@clayui/shared": "^3.1.2",
```
Comment (matuzalemsteles) [inline packages/clay-card/package.json:35]: Looking at this better, I think it would not be very useful to have `shared` as a dependency only for noop, I think we can remove this.

Comment (matuzalemsteles) [reply packages/clay-card/package.json:35]: cc @diegonvs

Comment (diegonvs) [reply packages/clay-card/package.json:35]: Sure, I'll remove
