### PR TITLE
fix: apply layout components throughout

### LINKED ISSUE #3255: Apply new @clayui/layout component

### PR DESCRIPTION
**Pull request by bryceosterhaus**
fixes #3255

### CODE REVIEW

File: packages/clay-card/src/CardWithUser.tsx [hunk 1]
```diff
@@ -7,6 +7,7 @@ import {ClayDropDownWithItems} from '@clayui/drop-down';
 import {ClayCheckbox} from '@clayui/form';
 import ClayIcon from '@clayui/icon';
 import ClayLabel from '@clayui/label';
+import * as ClayLayout from '@clayui/layout';
```
Comment (kresimir-coko) [inline packages/clay-card/src/CardWithUser.tsx:10]: This one is taken as an example, I've seen similar cases throughout the commit, but we seem to be importing all and then just using one subcomponent. In this case `<ClayLayout.ContentCol` on lines 140 & 163

File: packages/clay-management-toolbar/src/ManagementToolbar.tsx [hunk 2]
```diff
@@ -33,7 +34,9 @@ const ClayManagementToolbar: React.FunctionComponent<IProps> & {
 			}
 		)}
 	>
-		<div className="container-fluid container-fluid-max-xl">{children}</div>
+		<ClayLayout.ContainerFluid size="xl">
```
Comment (jbalsas) [inline packages/clay-management-toolbar/src/ManagementToolbar.tsx:37]: Is `size` really necessary as [it's the default](https://github.com/liferay/clay/blob/master/packages/clay-layout/src/ContainerFluid.tsx#L20) already?

File: packages/demos/stories/FormPage.tsx [hunk 3]
```diff
@@ -18,7 +19,7 @@ export default () => {
 	const [selectedItems, setSelectedItems] = React.useState<any>([]);
 
 	return (
-		<div className="container-fluid">
+		<ClayLayout.ContainerFluid>
```
Comment (jbalsas) [inline packages/demos/stories/FormPage.tsx:22]: Interestingly, this is would actually be `xl` because of the [defaults](https://github.com/liferay/clay/blob/master/packages/clay-layout/src/ContainerFluid.tsx#L20)

File: packages/demos/stories/Recharts.tsx [hunk 4]
```diff
@@ -537,7 +538,7 @@ storiesOf('Demos|Recharts', module)
 					</div>
 				</div>
 
-				<div className="container-fluid container-view">
+				<ClayLayout.ContainerFluid view>
```
Comment (jbalsas) [inline packages/demos/stories/Recharts.tsx:541]: Same, this would actually now be `xl` because of [defaults](https://github.com/liferay/clay/blob/master/packages/clay-layout/src/ContainerFluid.tsx#L20) which might not be so bad after all 😉

File: packages/clay-management-toolbar/src/ManagementToolbar.tsx (hunk 2 above)
Comment (bryceosterhaus) [reply packages/clay-management-toolbar/src/ManagementToolbar.tsx:37]: it is not necessary... i just forgot there was a default

File: packages/clay-card/src/CardWithUser.tsx (hunk 1 above)
Comment (bryceosterhaus) [reply packages/clay-card/src/CardWithUser.tsx]: Just updated to have a default export so that we don't have to do this

**Comment by bryceosterhaus** [comment]
Going to merge for release
