### PR TITLE
 fix(@clayui/data-provider): add LRUCache implementation

### LINKED ISSUE #2221: ClayDataProvider doesn't work on IE11
Importing `@clayui/data-provider` fails on IE11.

Error happens in [yallist](https://www.npmjs.com/package/yallist) dependency, in this line:

```js
Yallist.prototype[Symbol.iterator] = function* ()
```

Error in IE11 console is: `Expected '('`.

Generators are not being correctly transpiled to something IE11 understands.

Dependency tree: `#frontend-taglib-clay#@clayui#data-provider#lru-cache#yallist`

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes #2221

### CODE REVIEW

File: packages/clay-data-provider/src/LRUCache.ts [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+ * © 2019 Liferay, Inc. <https://liferay.com>
+ *
+ * SPDX-License-Identifier: BSD-3-Clause
+ */
+
+const DEFAULT_MAX_SIZE = 20;
+
+export class LRUCache<K, V> {
+	maxSize: number;
+	storage: Map<K, V>;
```
Comment (wincent) [inline packages/clay-data-provider/src/LRUCache.ts]: Shouldn't these be `private` or at least `_maxSize`/`_storage`? Otherwise I can break encapsulation.

File: packages/clay-data-provider/src/LRUCache.ts [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+	}
+
+	has(key: K) {
+		return this.storage.has(key);
+	}
+
+	get(key: K) {
+		const value = this.storage.get(key);
+
+		if (value) {
```
Comment (wincent) [inline packages/clay-data-provider/src/LRUCache.ts]: This check is probably not correct, because I could create a cache that stores booleans or other `false`-y values, and those wouldn't get bumped in the cache. That's why in [my implementation](https://github.com/wincent/masochist/blob/8ee6fc3704b204adae6dc3ad9baca5108a741637/src/server/LRUCache.js) that I showed you it does a `storage.has()` check instead.

File: packages/clay-data-provider/src/LRUCache.ts [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+			let count = this.maxSize - (this.storage.size - 1);
+			while (count) {
+				const {value} = iterator.next();
+				this.storage.delete(value);
+				count--;
+			}
+		}
+
+		this.storage.set(key, value);
+		return true;
```
Comment (wincent) [inline packages/clay-data-provider/src/LRUCache.ts]: Do you really want to return `true` here? It seems pointless to have a function that always returns `true` no matter what. Given that the cache is basically a `Map`, we could return `this` like `Map.prototype.set` does (that's what I did in [mine](https://github.com/wincent/masochist/blob/8ee6fc3704b204adae6dc3ad9baca5108a741637/src/server/LRUCache.js#L52) — this means you can chain multiple calls; eg. `new LRUCache().set('a', 1).set('b', 2)` — or just `undefined` (that's what [the other one](https://github.com/facebook/relay/commit/3f5d799fa8beb5f810f2bd37813674fc22598b74#diff-37a526caff576f11bac88a48c97391ebR49) I linked you to does).

Looking at how you are using this return value, I see it goes through many layers of indirection inside `useCache` and ultimately winds up discarded inside `useResource` when it does `cache.set(result)` and ignores the return value.

File: packages/clay-data-provider/src/__tests__/LRUCache.ts [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+let cache: LRUCache<string, {}>;
+
+describe('LRUCache', () => {
+	beforeEach(() => {
+		cache = new LRUCache(3);
+	});
+
+	afterEach(() => {
+		cache.reset();
+	});
```
Comment (wincent) [inline packages/clay-data-provider/src/__tests__/LRUCache.ts]: Delete this; you don't need to reset the object because you get a brand new object anyway each time.

File: packages/clay-data-provider/src/__tests__/LRUCache.ts [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+
+	it('throw error if initialized with maxSize 0', () => {
```
Comment (wincent) [inline packages/clay-data-provider/src/__tests__/LRUCache.ts]: "throw error if" isn't grammatical, so please change to: "throws if" or "throws an error if".

Same in the next example.

File: packages/clay-data-provider/src/__tests__/LRUCache.ts [hunk 6]
```diff
@@ -0,0 +1,63 @@
...
+	it('returns undefined for undefined key', () => {
+		expect(cache.get('foo')).toBe(undefined);
+	});
+
+	it('returns value for present value', () => {
+		cache.set('foo', 'f');
+		expect(cache.get('foo')).toBe('f');
+	});
+
+	it('least recently set', () => {
```
Comment (wincent) [inline packages/clay-data-provider/src/__tests__/LRUCache.ts]: Can you change this into a sentence that reads correct when read out loud? ie. "it something something something". I don't actually know what you are testing here, or in the next one.

Compare that with [these tests I wrote here](https://github.com/wincent/masochist/blob/8ee6fc3704b204adae6dc3ad9baca5108a741637/src/server/__tests__/LRUCache-test.js#L41-L58), where the `it` and the comments describe what is actually expected and happening:

```javascript
describe('set()', () => {
  it('evicts old items', () => {
    // Populate the cache.
    cache.set('a', '#a');
    cache.set('b', '#b');
    cache.set('c', '#c');
    expect(cache.has('a')).toBe(true);
    expect(cache.has('b')).toBe(true);
    expect(cache.has('c')).toBe(true);

    // Cause an eviction.
    cache.set('d', '#d');
    expect(cache.has('a')).toBe(false);
    expect(cache.has('b')).toBe(true);
    expect(cache.has('c')).toBe(true);
    expect(cache.has('d')).toBe(true);
  });
});
```

File: packages/clay-data-provider/src/LRUCache.ts (hunk 2 above)
Comment (matuzalemsteles) [reply packages/clay-data-provider/src/LRUCache.ts]: Hmm, I had forgotten about these values ​​that may be here, thanks for this @wincent.

File: packages/clay-data-provider/src/LRUCache.ts (hunk 1 above)
Comment (matuzalemsteles) [reply packages/clay-data-provider/src/LRUCache.ts]: Oh yeah, I'm hoping no one will touch the instance of `LRUCache`, I tried to use `Symbol` as a key in `useCache` to avoid these kinds of things. But I was thinking of going with `_maxSize`/`_storage` but I find the underline so horrible for that 😅, I will go with `private` for more security here.

File: packages/clay-data-provider/src/LRUCache.ts (hunk 3 above)
Comment (matuzalemsteles) [reply packages/clay-data-provider/src/LRUCache.ts]: Hmm, good question, this would probably be a trade-off in returning `true` or `undefined` in the end would be the same as returning `true` even if you don't use it but the purpose is just another meaning of showing that everything will always work out and Assuming that the method actually did is `true` then `true`, `1`... it would make little sense to return `undefined`, `NuN`, `false` because they are treated as negative or nothing happened etc...

I think in the end I prefer to keep the chainable, it seems to be more useful but maybe not use here, so I prefer to go with the `undefined` return here to be in the middle ground 🙂.

File: packages/clay-data-provider/src/__tests__/LRUCache.ts (hunk 4 above)
Comment (matuzalemsteles) [reply packages/clay-data-provider/src/__tests__/LRUCache.ts]: Oh yeah, I guess I just put it in my mind that `new LRUCache` would only run once... even if it's `beforeEach` 😂

File: packages/clay-data-provider/src/LRUCache.ts (hunk 1 above)
Comment (wincent) [reply packages/clay-data-provider/src/LRUCache.ts]: Yeah, seeing as this is a TypeScript project, `private` (and `#` private class fields once those get implemented) is probably preferable over `_` prefix. Even with `private` it is not literally private, it is only advisory. TypeScript will tell you if you do it wrong, but you can cast away:

```javascript
// Property 'x' is private and only accessible within class 'Thing'.
thing.x = 11;

// 😃 
(thing as any).x = 11;
```

But still, its good to put some measure in place to stop me going `cache.storage.clear()` from the outside.

**Comment by matuzalemsteles** [comment]
Hey guys, I'm going ahead with this, I applied the requested changes.
