### PR TITLE
fix(@clayui/navigation-bar): fix error when rendering only one Item

### LINKED ISSUE #4517: ClayNavigationBar throws an exception if only a single item is provided
## Is there an example you can provide via codesandbox.com?
Screenshot from 2021-12-17 19-51-19

```jsx
const Component = () => {
  return (
    <ClayNavigationBar triggerLabel="Item 1" spritemap={spritemap}>
      <ClayNavigationBar.Item active>
        <ClayLink className="nav-link" displayType="unstyled">
          Item 1
        </ClayLink>
      </ClayNavigationBar.Item>
    </ClayNavigationBar>
  );
};



render(<Component />);
```

```console
DevTools failed to load source map: Could not load content for http://localhost:8080/main.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index.js:62 Uncaught TypeError: children.filter is not a function
    at ClayNavigationBar (index.js:62)
    at renderWithHooks (react-dom.development.js:16260)
    at mountIndeterminateComponent (react-dom.development.js:18794)
    at beginWork$1 (react-dom.development.js:20162)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at beginWork$$1 (react-dom.development.js:25780)
    at performUnitOfWork (react-dom.development.js:24695)
    at workLoopSync (react-dom.development.js:24671)
ClayNavigationBar @ index.js:62
renderWithHooks @ react-dom.development.js:16260
mountIndeterminateComponent @ react-dom.development.js:18794
beginWork$1 @ react-dom.development.js:20162
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
beginWork$$1 @ react-dom.development.js:25780
performUnitOfWork @ react-dom.development.js:24695
workLoopSync @ react-dom.development.js:24671
performSyncWorkOnRoot @ react-dom.development.js:24270
scheduleUpdateOnFiber @ react-dom.development.js:23698
updateContainer @ react-dom.development.js:27103
(anonymous) @ react-dom.development.js:27528
unbatchedUpdates @ react-dom.development.js:24433
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27527
render @ react-dom.development.js:27608
render @ render.tsx:88
_default @ render.es.js:21
(anonymous) @ manage?p_p_id=com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_mvcRenderCommandName=%2Fadmin%2Fedit_form_instance&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_redirect=%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_v_l_s_g_id%3D20123&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_groupId=20123:4284
(anonymous) @ manage?p_p_id=com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_mvcRenderCommandName=%2Fadmin%2Fedit_form_instance&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_redirect=%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_v_l_s_g_id%3D20123&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_groupId=20123:4285
(anonymous) @ loader.js:463
(anonymous) @ loader.js:427
Promise.then (async)
value @ loader.js:396
(anonymous) @ manage?p_p_id=com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_mvcRenderCommandName=%2Fadmin%2Fedit_form_instance&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_redirect=%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_v_l_s_g_id%3D20123&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_groupId=20123:4279
react_devtools_backend.js:4045 The above error occurred in the <ClayNavigationBar> component:
    in ClayNavigationBar (created by main)
    in div (created by main)
    in main

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
overrideMethod @ react_devtools_backend.js:4045
logCapturedError @ react-dom.development.js:21843
logError @ react-dom.development.js:21880
update.callback @ react-dom.development.js:23232
callCallback @ react-dom.development.js:13829
commitUpdateEffects @ react-dom.development.js:13867
commitUpdateQueue @ react-dom.development.js:13857
commitLifeCycles @ react-dom.development.js:22160
commitLayoutEffects @ react-dom.development.js:25344
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
commitRootImpl @ react-dom.development.js:25082
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
commitRoot @ react-dom.development.js:24922
finishSyncRender @ react-dom.development.js:24329
performSyncWorkOnRoot @ react-dom.development.js:24307
scheduleUpdateOnFiber @ react-dom.development.js:23698
updateContainer @ react-dom.development.js:27103
(anonymous) @ react-dom.development.js:27528
unbatchedUpdates @ react-dom.development.js:24433
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27527
render @ react-dom.development.js:27608
render @ render.tsx:88
_default @ render.es.js:21
(anonymous) @ manage?p_p_id=com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_mvcRenderCommandName=%2Fadmin%2Fedit_form_instance&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_redirect=%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_v_l_s_g_id%3D20123&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_groupId=20123:4284
(anonymous) @ manage?p_p_id=com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_mvcRenderCommandName=%2Fadmin%2Fedit_form_instance&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_redirect=%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_v_l_s_g_id%3D20123&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_groupId=20123:4285
(anonymous) @ loader.js:463
(anonymous) @ loader.js:427
Promise.then (async)
value @ loader.js:396
(anonymous) @ manage?p_p_id=com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_mvcRenderCommandName=%2Fadmin%2Fedit_form_instance&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_redirect=%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_v_l_s_g_id%3D20123&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_groupId=20123:4279
react_devtools_backend.js:4045 TypeError: children.filter is not a function
    at ClayNavigationBar (index.js:62)
    at renderWithHooks (react-dom.development.js:16260)
    at mountIndeterminateComponent (react-dom.development.js:18794)
    at beginWork$1 (react-dom.development.js:20162)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at beginWork$$1 (react-dom.development.js:25780)
    at performUnitOfWork (react-dom.development.js:24695)
    at workLoopSync (react-dom.development.js:24671)
overrideMethod @ react_devtools_backend.js:4045
(anonymous) @ manage?p_p_id=com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_mvcRenderCommandName=%2Fadmin%2Fedit_form_instance&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_redirect=%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_v_l_s_g_id%3D20123&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_groupId=20123:4287
(anonymous) @ loader.js:463
(anonymous) @ loader.js:427
Promise.then (async)
value @ loader.js:396
(anonymous) @ manage?p_p_id=com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_mvcRenderCommandName=%2Fadmin%2Fedit_form_instance&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_redirect=%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_v_l_s_g_id%3D20123&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_groupId=20123:4279
aui.js:185 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ aui.js:185
_createWrapper @ event-base.js:730
_attach @ event-base.js:825
on @ event-custom-base.js:1758
on @ event-custom-base.js:1726
(anonymous) @ event-custom-base.js:1711
YArray.each.YArray.forEach @ aui.js:2525
dispatch @ oop.js:49
Y.each @ oop.js:238
on @ event-custom-base.js:1698
unsequester @ oop.js:141
newPrototype.<computed>.replacements.<computed> @ oop.js:119
init @ product_navigation_control_menu.js:31
(anonymous) @ manage?p_p_id=com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_mvcRenderCommandName=%2Fadmin%2Fedit_form_instance&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_redirect=%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_v_l_s_g_id%3D20123&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_groupId=20123:4948
(anonymous) @ manage?p_p_id=com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_mvcRenderCommandName=%2Fadmin%2Fedit_form_instance&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_redirect=%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_v_l_s_g_id%3D20123&_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_groupId=20123:4967
args.<computed> @ aui_sandbox.js:37
_notify @ aui.js:1108
(anonymous) @ aui.js:1245
_notify @ aui.js:1108
(anonymous) @ aui.js:1245
_notify @ aui.js:1108
handleLoader @ aui.js:1253
_use @ aui.js:1344
handleLoader @ aui.js:1243
_finish @ aui.js:8231
_onSuccess @ aui.js:8280
complete @ aui.js:8519
_insert @ aui.js:8528
complete @ aui.js:8513
onSuccess @ aui.js:8581
_finish @ aui.js:4997
_next @ aui.js:5195
_progress @ aui.js:5303
onLoad @ aui.js:5095
Show 4 more frames
aui-timer.js:318 [Violation] 'setTimeout' handler took 66ms
```
## What are the steps to reproduce?
Render a `ClayNavigationBar` with a single item

## What is the expected result?
Properly display the ClayNavigationBar bar with a single item inside

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.40.0  |
| React |  16.12.0 |

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes #4517

### CODE REVIEW

File: packages/clay-navigation-bar/src/index.tsx [hunk 1]
```diff
@@ -48,9 +48,10 @@ const ClayNavigationBar: React.FunctionComponent<IProps> & {
 }: IProps) => {
 	const [expanded, setExpanded] = React.useState(false);
 
-	const activeElementsCount = children.filter(
+	const activeElementsCount = React.Children.map(
+		children,
 		(child) => child.props.active
-	).length;
+	).filter(Boolean).length;
```
Comment (julien) [inline packages/clay-navigation-bar/src/index.tsx:54]: @matuzalemsteles I think we also need to update the [props](https://github.com/liferay/clay/blob/7fd169fea7aec47018577ee17ba90931dee7c7df/packages/clay-navigation-bar/src/index.tsx#L21) for `ClayNavigationBar` so that it also accepts one item, because right now it looks like this

```jsx
	children: Array<React.ReactElement<React.ComponentProps<typeof Item>>>;
```

And I'm assuming we want 

```jsx
	children: Array<React.ReactElement<React.ComponentProps<typeof Item>>> | React.ReactElement<React.ComponentProps<typeof Item>>;
```

Since you're on PTO right now, I'm not expecting you to reply, but at least I left a "trace"

**Review by julien — CHANGES_REQUESTED** [review]
Will submit a new pull request

**Review by julien — APPROVED** [review]

File: packages/clay-navigation-bar/src/index.tsx (hunk 1 above)
Comment (matuzalemsteles) [reply packages/clay-navigation-bar/src/index.tsx:56]: Yeah, I had to update that in the prop too, thanks.

Comment (julien) [reply packages/clay-navigation-bar/src/index.tsx:56]: no problem
