### PR TITLE
fix(@clayui/shared): useTransitionHeight should still expand and collapse if transitions aren't supported

### LINKED ISSUE #3637: ClayPanel: Panel does not Collapse/Close after second hit on Microsoft Edge W10
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

here: https://codesandbox.io/s/agitated-cherry-r6rdt?file=/src/App.js

## What are the steps to reproduce?

1. Click on Panel to Collapse/Close

## What is the expected result?

1. The panel should Collapse/Close after hit on Panel
2. A transition slide should be shown

## Environment

| Tech  | Version |
| ----- | ------- |
| @clayui/panel  | v3.2.3  |
| React | v16.12       |
| Microsoft Edge Windows 10 |  84.0.522.63 (Latest) |

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes #3637, From #3677

I made some changes on top of @pat270's PR, instead of implementing a fallback in support of the `transitionEnd` event, I decided to remove it and rewrite the implementation on top of `setTimeout`.

### CODE REVIEW

**Comment by pat270** [comment]
LGTM

File: packages/clay-navigation-bar/src/__tests__/index.tsx [hunk 1]
```diff
@@ -143,10 +145,16 @@ describe('ClayNavigationBar', () => {
 		);
 
 		fireEvent.click(getByTestId('navbarToggler'), 'Trigger Label');
-		fireEvent.transitionEnd(getByTestId('NavigationBarDropdown'));
+
+		act(() => {
+			jest.runAllTimers();
+		});
```
Comment (bryceosterhaus) [inline packages/clay-navigation-bar/src/__tests__/index.tsx:151]: How come you have to wrap this in an act?

**Review by bryceosterhaus — COMMENTED** [review]
Looks good to me, just had one question on the tests

File: packages/clay-navigation-bar/src/__tests__/index.tsx (hunk 1 above)
Comment (matuzalemsteles) [reply packages/clay-navigation-bar/src/__tests__/index.tsx:151]: This was throwing some errors on the console, as we are using `setTimeout` and has scheduled a function that will change the states, this probably causes new renderings later and we have to wrap this within an `act`.

Comment (bryceosterhaus) [reply packages/clay-navigation-bar/src/__tests__/index.tsx:151]: Hmm, that seems odd. I would think you could just run it without the `act`.

Oh well, im fine with merging!

Comment (matuzalemsteles) [reply packages/clay-navigation-bar/src/__tests__/index.tsx:151]: Yeah, I remember that I had a lot of problems with this and I only solved it by adding `act`, otherwise we will see a lot of warnings on the console like this one.

Screen Shot 2020-09-24 at 18 32 39

I think it makes sense since we will be running all the timeouts that will cause some rendering.

**Comment by matuzalemsteles** [comment]
@bryceosterhaus I will go ahead with this PR according to your last message, in case you see any problems we can create another PR for this.
