### PR TITLE
fix(@clayui/layout): add ability to disable fluid-max-* class

### LINKED ISSUE #3313: New ClayLayout: `<ClayLayout.ContainerFluid>` cannot display only the class `container-fluid`
### New ClayLayout: `<ClayLayout.ContainerFluid>` cannot display only the class `container-fluid`
https://storybook.clayui.com/iframe.html?id=components-claylayout--row-positioning

## What are the steps to reproduce?

We tried by adding:
`<ClayLayout.ContainerFluid fluidSize={false}>``
it does not work

## What is the expected result?

Be able to remove the default class:
`container-fluid-max-xl`

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | master  |
| React |         |

### PR DESCRIPTION
**Pull request by bryceosterhaus**
fixes #3313

### CODE REVIEW

File: packages/clay-layout/src/__tests__/index.tsx [hunk 1]
```diff
@@ -96,4 +96,18 @@ describe('ClayLayout', () => {
...
+			<>
+				<ClayLayout.ContainerFluid size={false}>
+					{'test'}
+				</ClayLayout.ContainerFluid>
+			</>
+		);
+
+		expect(
+			container.querySelector('.container-fluid')!.classList
+		).toMatchSnapshot();
```
Comment (wincent) [inline packages/clay-layout/src/__tests__/index.tsx:111]: It seems a shame to have to look at a snapshot file just to see what we expect the class list to look like (ie. a single class, `.container-fluid`). The trouble with snapshots is generally that they say too much (which means it can be hard to know whether an update to them is legitimate or evidence of breakage); but this one suffers from the opposite problem — that it doesn't say enough to justify being a snapshot. Can we inline this and avoid the snapshot?

Comment (bryceosterhaus) [reply packages/clay-layout/src/__tests__/index.tsx:111]: Good call, just updated
